I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    $ Inventory[0].AddItem()
  File "game/script.rpy", line 16, in <module>
    $ Inventory[0].AddItem()
  File "game/scripts/events.rpy", line 55, in AddItem
    if CurrentWeight + self.weight > MaxWeight:
NameError: global name 'CurrentWeight' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    $ Inventory[0].AddItem()
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    $ Inventory[0].AddItem()
  File "game/scripts/events.rpy", line 55, in AddItem
    if CurrentWeight + self.weight > MaxWeight:
NameError: global name 'CurrentWeight' is not defined

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.9.2142
Thundy Inventory 1.0
Tue Oct 19 21:35:41 2021
