I'm sorry, but an uncaught exception occurred.

While loading <'Scale' <'Image' u'bg01.jpeg'> 1920 1080 True>:
  File "game/script.rpy", line 14, in script
    menu:
IOError: Couldn't find file 'bg01.jpeg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    menu:
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/ast.py", line 1688, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/exports.py", line 1062, in menu
    rv = renpy.store.menu(new_items)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/exports.py", line 1298, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/core.py", line 3834, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/core.py", line 2555, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 492, in renpy.display.render.render_screen
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/layout.py", line 824, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/layout.py", line 824, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/layout.py", line 824, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/transform.py", line 733, in render
    return transform_render(self, width, height, st, at)
  File "accelerator.pyx", line 187, in renpy.display.accelerator.transform_render
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/image.py", line 501, in render
    return wrap_render(self.target, width, height, st, at)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/image.py", line 307, in wrap_render
    rend = render(child, w, h, st, at)
  File "render.pyx", line 170, in renpy.display.render.render
  File "render.pyx", line 263, in renpy.display.render.render
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/im.py", line 607, in render
    return cache.get(self, render=True)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/im.py", line 271, in get
    surf = image.load()
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/im.py", line 858, in load
    child = cache.get(self.image)
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/im.py", line 271, in get
    surf = image.load()
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/display/im.py", line 688, in load
    raise e
IOError: Couldn't find file 'bg01.jpeg'.

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.9.2142
Thundy Inventory 1.0
Tue Oct 19 18:09:32 2021
